<a href="https://colab.research.google.com/github/unmiulast/my-first-repo/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy==2.0.2

In [3]:
import numpy as np

In [4]:
# 配列のパターン
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a*2)

[11 22 33]
[2 4 6]


ベクトル演算をしている

In [5]:
# リストのパターン
# a = [1, 2, 3]
# b = [10, 20, 30]
# print(a + b)
# print(a*2)

配列型とリスト型の違い

In [6]:
a[1]
a[:2]

array([1, 2])

In [7]:
# 統計量計算

a = np.array([1, 2, 3, 4, 5])
np.sum(a) #総和
np.mean(a) #平均値
np.median(a) #中央値
np.std(a) #標準偏差

np.float64(1.4142135623730951)

In [8]:
# 多次元配列

A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
A.shape

(3, 2)

◯行◯列

In [10]:
A.T.shape

(2, 3)

転置

In [11]:
# 実際の例
scores = np.array([80, 90, 75, 100])

mean = np.mean(scores)
scores - mean

array([ -6.25,   3.75, -11.25,  13.75])

In [12]:
# 配列の作成
np.random.rand(3, 2)
np.zeros((3, 2))
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
np.random.rand(3, 2)


array([[0.30477241, 0.02405771],
       [0.29832627, 0.02019164],
       [0.07070215, 0.26707209]])

In [14]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])